brand:
  docs_url: https://docs.searxng.org/
  issue_url: https://github.com/dcjk2010/SearXNGforWindows/issues
  public_instances: https://searx.space
  wiki_url: https://github.com/dcjk2010/SearXNGforWindows/wiki
categories_as_tabs:
  general: null
  files: null
  images: null
  it: null
  map: null
  music: null
  news: null
  science: null
  social media: null
  videos: null
default_doi_resolver: oadoi.org
doi_resolvers:
  doi.org: https://doi.org/
  oadoi.org: https://oadoi.org/
  sci-hub.ru: https://sci-hub.ru/
  sci-hub.se: https://sci-hub.se/
  sci-hub.st: https://sci-hub.st/
engines:
- disabled: false
  engine: ansa
  name: ansa
  shortcut: ans
- disabled: false
  engine: il_post
  name: il post
  shortcut: pst
- categories:
  - videos
  disabled: false
  engine: naver
  name: naver videos
  naver_category: videos
  shortcut: nvrv
- engine: reuters
  name: reuters
  shortcut: reu
  disabled: false
- categories:
  - news
  - web
  disabled: false
  engine: mojeek
  name: mojeek news
  paging: false
  search_type: news
  shortcut: mjknews
general:
  contact_url: false
  debug: false
  donation_url: false
  enable_metrics: true
  instance_name: SearXNG for Windows
  open_metrics: ''
  privacypolicy_url: false
outgoing:
  useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/125.0.0.0 Safari/537.36
  enable_http2: true
  pool_connections: 100
  pool_maxsize: 20
  request_timeout: 10.0
  useragent_suffix: ''
plugins:
  searx.plugins.ahmia_filter.SXNGPlugin:
    active: true
  searx.plugins.calculator.SXNGPlugin:
    active: true
  searx.plugins.hash_plugin.SXNGPlugin:
    active: true
  searx.plugins.hostnames.SXNGPlugin:
    active: true
  searx.plugins.infinite_scroll.SXNGPlugin:
    active: false
  searx.plugins.oa_doi_rewrite.SXNGPlugin:
    active: false
  searx.plugins.self_info.SXNGPlugin:
    active: true
  searx.plugins.time_zone.SXNGPlugin:
    active: true
  searx.plugins.tor_check.SXNGPlugin:
    active: false
  searx.plugins.tracker_url_remover.SXNGPlugin:
    active: true
  searx.plugins.unit_converter.SXNGPlugin:
    active: true
search:
  autocomplete: bing
  autocomplete_min: 4
  ban_time_on_fail: 5
  default_lang: auto
  favicon_resolver: ''
  formats:
  - html
  - json
  max_ban_time_on_fail: 120
  safe_search: 1
  suspended_times:
    SearxEngineAccessDenied: 180
    SearxEngineCaptcha: 3600
    SearxEngineTooManyRequests: 180
    cf_SearxEngineAccessDenied: 86400
    cf_SearxEngineCaptcha: 1296000
    recaptcha_SearxEngineCaptcha: 604800
server:
  base_url: false
  bind_address: 127.0.0.1
  default_http_headers:
    Referrer-Policy: no-referrer
    X-Content-Type-Options: nosniff
    X-Download-Options: noopen
    X-Robots-Tag: noindex, nofollow
  http_protocol_version: '1.0'
  image_proxy: false
  limiter: false
  method: POST
  port: 8888
  public_instance: false
  secret_key: your_random_dcjk_2010
ui:
  center_alignment: false
  default_locale: ''
  default_theme: simple
  hotkeys: default
  query_in_title: false
  search_on_category_select: true
  static_path: ''
  templates_path: ''
  theme_args:
    simple_style: auto
  url_formatting: pretty
valkey:
  url: false
